import ColorVariables from '../stylesheets/Colors.scss';

const elements = [
  { id: 0, label: `<b>root</b>`, title: "root node", color: ColorVariables.root, widthConstraint: 150},
  { id: 1, label: `<b>H</b>`, title: "Hydrogen", color: ColorVariables.nonMetal, weight: 1.008},
  { id: 2, label: `<b>He</b>`, title: "Helium", color: ColorVariables.nobleGas, weight: 4.0026},
  { id: 3, label: `<b>Li</b>`, title: "Lithium", color: ColorVariables.alkaliMetal, weight: 6.94},
  { id: 4, label: `<b>Be</b>`, title: "Beryllium", color: ColorVariables.alkaliMetal, weight: 9.0122},
  { id: 5, label: `<b>B</b>`, title: "Boron", color: ColorVariables.metalloid, weight: 10.81},
  { id: 6, label: `<b>C</b>`, title: "Carbon", color: ColorVariables.nonMetal, weight: 12.011},
  { id: 7, label: `<b>N</b>`, title: "Nitrogen", color: ColorVariables.nonMetal, weight: 14.007},
  { id: 8, label: `<b>O</b>`, title: "Oxygen", color: ColorVariables.nonMetal, weight: 15.999},
  { id: 9, label: `<b>F</b>`, title: "Fluorine", color: ColorVariables.nonMetal, weight: 18.998},
  { id: 10, label: `<b>Ne</b>`, title: "Neon", color: ColorVariables.nobleGas, weight: 20.180},
  { id: 11, label: `<b>Na</b>`, title: "Sodium", color: ColorVariables.alkaliMetal, weight: 22.990},
  { id: 12, label: `<b>Mg</b>`, title: "Magnesium", color: ColorVariables.alkaliMetal, weight: 24.305},
  { id: 13, label: `<b>Al</b>`, title: "Aluminum", color: ColorVariables.postTransitionMetal, weight: 26.982},
  { id: 14, label: `<b>Si</b>`, title: "Silicon", color: ColorVariables.metalloid, weight:28.085},
  { id: 15, label: `<b>P</b>`, title: "Phosphorus", color: ColorVariables.nonMetal, weight: 30.974},
  { id: 16, label: `<b>S</b>`, title: "Sulfur", color: ColorVariables.nonMetal, weight: 32.06},
  { id: 17, label: `<b>Cl</b>`, title: "Chlorine", color: ColorVariables.nonMetal, weight: 35.45},
  { id: 18, label: `<b>Ar</b>`, title: "Argon", color: ColorVariables.nobleGas, weight:39.948},
  { id: 19, label: `<b>K</b>`, title: "Potassium", color: ColorVariables.alkaliMetal, weight: 39.098},
  { id: 20, label: `<b>Ca</b>`, title: "Calcium", color: ColorVariables.alkaliMetal, weight: 40.078},
  { id: 21, label: `<b>Sc</b>`, title: "Scandium", color: ColorVariables.transitionMetal, weight: 44.956},
  { id: 22, label: `<b>Ti</b>`, title: "Titanium", color: ColorVariables.transitionMetal, weight: 47.867},
  { id: 23, label: `<b>V</b>`, title: "Vanadium", color: ColorVariables.transitionMetal, weight: 50.942},
  { id: 24, label: `<b>Cr</b>`, title: "Chromium", color: ColorVariables.transitionMetal, weight: 51.996},
  { id: 25, label: `<b>Mn</b>`, title: "Manganese", color: ColorVariables.transitionMetal, weight: 54.938},
  { id: 26, label: `<b>Fe</b>`, title: "Iron", color: ColorVariables.transitionMetal, weight: 55.845},
  { id: 27, label: `<b>Co</b>`, title: "Cobalt", color: ColorVariables.transitionMetal, weight: 58.933},
  { id: 28, label: `<b>Ni</b>`, title: "Nickel", color: ColorVariables.transitionMetal, weight: 58.693},
  { id: 29, label: `<b>Cu</b>`, title: "Copper", color: ColorVariables.transitionMetal, weight: 63.546},
  { id: 30, label: `<b>Zn</b>`, title: "Zinc", color: ColorVariables.transitionMetal, weight: 65.38},
  { id: 31, label: `<b>Ga</b>`, title: "Gallium", color: ColorVariables.transitionMetal, weight: 69.723},
  { id: 32, label: `<b>Ge</b>`, title: "Germanium", color: ColorVariables.transitionMetal, weight: 72.630},
  { id: 33, label: `<b>As</b>`, title: "Arsenic", color: ColorVariables.transitionMetal, weight: 74.922},
  { id: 34, label: `<b>Se</b>`, title: "Selenium", color: ColorVariables.transitionMetal, weight: 78.971},
  { id: 35, label: `<b>Br</b>`, title: "Bromine", color: ColorVariables.transitionMetal, weight: 79.904},
  { id: 36, label: `<b>Kr</b>`, title: "Krypton", color: ColorVariables.transitionMetal, weight:83.798},
  { id: 37, label: `<b>Rb</b>`, title: "Rubidium", color: ColorVariables.transitionMetal, weight: 85.468},
  { id: 38, label: `<b>Sr</b>`, title: "Strontium", color: ColorVariables.transitionMetal, weight: 87.62},
  { id: 39, label: `<b>Y</b>`, title: "Yttrium", color: ColorVariables.transitionMetal, weight: 88.90},
  { id: 40, label: `<b>Zr</b>`, title: "Zirconium", color: ColorVariables.transitionMetal, weight: 91.224},
  { id: 41, label: `<b>Nb</b>`, title: "Niobium", color: ColorVariables.transitionMetal, weight: 92.906},
  { id: 42, label: `<b>Mo</b>`, title: "Molybdeum", color: ColorVariables.transitionMetal, weight: 95.95},
  { id: 43, label: `<b>Tc</b>`, title: "Technetium", color: ColorVariables.transitionMetal, weight: 98},
  { id: 44, label: `<b>Ru</b>`, title: "Ruthenium", color: ColorVariables.transitionMetal, weight:101.07},
  { id: 45, label: `<b>Rh</b>`, title: "Rhodium", color: ColorVariables.transitionMetal, weight:102.91},
  { id: 46, label: `<b>Pd</b>`, title: "Palladium", color: ColorVariables.transitionMetal, weight: 106.42},
  { id: 47, label: `<b>Ag</b>`, title: "Silver", color: ColorVariables.transitionMetal, weight: 107.87},
  { id: 48, label: `<b>Cd</b>`, title: "Cadmium", color: ColorVariables.transitionMetal, weight: 112.41},
  { id: 49, label: `<b>In</b>`, title: "Indium", color: ColorVariables.transitionMetal, weight: 114.82},
  { id: 50, label: `<b>Sn</b>`, title: "Tin", color: ColorVariables.transitionMetal, weight: 118.71},
  { id: 51, label: `<b>Sb</b>`, title: "Antimony", color: ColorVariables.transitionMetal, weight: 121.76},
  { id: 52, label: `<b>Te</b>`, title: "Tellurium", color: ColorVariables.transitionMetal, weight: 127.60},
  { id: 53, label: `<b>I</b>`, title: "Iodine", color: ColorVariables.transitionMetal, weight: 126.90},
  { id: 54, label: `<b>Xe</b>`, title: "Xenon", color: ColorVariables.transitionMetal, weight: 131.29},  
  { id: 55, label: `<b>Cs</b>`, title: "Caesium", color: ColorVariables.transitionMetal, weight: 132.91},
  { id: 56, label: `<b>Ba</b>`, title: "Barium", color: ColorVariables.transitionMetal, weight: 137.33},
  { id: 57, label: `<b>La</b>`, title: "Lanthanium", color: ColorVariables.lanthanide, weight: 138.91},
  { id: 58, label: `<b>Ce</b>`, title: "Cerium", color: ColorVariables.lanthanide, weight: 140.12},
  { id: 59, label: `<b>Pr</b>`, title: "Praseodymium", color: ColorVariables.lanthanide, weight: 140.91},
  { id: 60, label: `<b>Nd</b>`, title: "Neodymium", color: ColorVariables.lanthanide, weight: 144.24},
  { id: 61, label: `<b>Pm</b>`, title: "Prometheum", color: ColorVariables.lanthanide, weight: 145},
  { id: 62, label: `<b>Sm</b>`, title: "Samarium", color: ColorVariables.lanthanide, weight: 150.36},
  { id: 63, label: `<b>Eu</b>`, title: "Europium", color: ColorVariables.lanthanide, weight: 151.96},
  { id: 64, label: `<b>Gd</b>`, title: "Gadolinium", color: ColorVariables.lanthanide, weight: 157.25},
  { id: 65, label: `<b>Tb</b>`, title: "Terbium", color: ColorVariables.lanthanide, weight: 158.93},
  { id: 66, label: `<b>Dy</b>`, title: "Dysprosium", color: ColorVariables.lanthanide, weight: 162.50},
  { id: 67, label: `<b>Ho</b>`, title: "Holmium", color: ColorVariables.lanthanide, weight: 164.93},
  { id: 68, label: `<b>Er</b>`, title: "Erbium", color: ColorVariables.lanthanide, weight: 167.26},
  { id: 69, label: `<b>Tm</b>`, title: "Thulium", color: ColorVariables.lanthanide, weight: 168.93},
  { id: 70, label: `<b>Yb</b>`, title: "Ytterbium", color: ColorVariables.lanthanide, weight: 173.05},
  { id: 71, label: `<b>Lu</b>`, title: "Lutetium", color: ColorVariables.lanthanide, weight: 174.97},
  { id: 89, label: `<b>Ac</b>`, title: "Actinium", color: ColorVariables.actinide, weight: 227},
  { id: 90, label: `<b>Th</b>`, title: "Thorium", color: ColorVariables.actinide, weight: 232.04},
]

export default elements;