import ColorVariables from '../stylesheets/Colors.scss';

const elements = [
  { label: `<b>root</b>`, title: "root node", color: ColorVariables.root, widthConstraint: 150 },
  { id: 1, label: `<b>H</b>`, title: "Hydrogen", color: ColorVariables.nonMetal},
  { id: 2, label: `<b>He</b>`, title: "Helium", color: ColorVariables.nobleGas},
  { id: 3, label: `<b>Li</b>`, title: "Lithium", color: ColorVariables.alkaliMetal},
  { id: 4, label: `<b>Be</b>`, title: "Beryllium", color: ColorVariables.alkaliMetal},
  { id: 5, label: `<b>B</b>`, title: "Boron", color: ColorVariables.metalloid},
  { id: 6, label: `<b>C</b>`, title: "Carbon", color: ColorVariables.nonMetal},
  { id: 7, label: `<b>N</b>`, title: "Nitrogen", color: ColorVariables.nonMetal},
  { id: 8, label: `<b>O</b>`, title: "Oxygen", color: ColorVariables.nonMetal},
  { id: 9, label: `<b>F</b>`, title: "Fluorine", color: ColorVariables.nonMetal},
  { id: 10, label: `<b>Ne</b>`, title: "Neon", color: ColorVariables.nobleGas},
  { id: 11, label: `<b>Na</b>`, title: "Sodium", color: ColorVariables.alkaliMetal},
  { id: 12, label: `<b>Mg</b>`, title: "Magnesium", color: ColorVariables.alkaliMetal},
  { id: 13, label: `<b>Al</b>`, title: "Aluminum", color: ColorVariables.postTransitionMetal},
  { id: 14, label: `<b>Si</b>`, title: "Silicon", color: ColorVariables.metalloid},
  { id: 15, label: `<b>P</b>`, title: "Phosphorus", color: ColorVariables.nonMetal},
  { id: 16, label: `<b>S</b>`, title: "Sulfur", color: ColorVariables.nonMetal},
  { id: 17, label: `<b>Cl</b>`, title: "Chlorine", color: ColorVariables.nonMetal},
  { id: 18, label: `<b>Ar</b>`, title: "Argon", color: ColorVariables.nobleGas},
  { id: 19, label: `<b>K</b>`, title: "Potassium", color: ColorVariables.alkaliMetal},
  { id: 20, label: `<b>Ca</b>`, title: "Calcium", color: ColorVariables.alkaliMetal},
  { id: 21, label: `<b>Sc</b>`, title: "Scandium", color: ColorVariables.transitionMetal},
  { id: 22, label: `<b>Ti</b>`, title: "Titanium", color: ColorVariables.transitionMetal},
  { id: 23, label: `<b>V</b>`, title: "Vanadium", color: ColorVariables.transitionMetal},
  { id: 24, label: `<b>Cr</b>`, title: "Chromium", color: ColorVariables.transitionMetal},
  { id: 25, label: `<b>Mn</b>`, title: "Manganese", color: ColorVariables.transitionMetal},
  { id: 26, label: `<b>Fe</b>`, title: "Iron", color: ColorVariables.transitionMetal},
  { id: 27, label: `<b>Co</b>`, title: "Cobalt", color: ColorVariables.transitionMetal},
  { id: 28, label: `<b>Ni</b>`, title: "Nickel", color: ColorVariables.transitionMetal},
  { id: 29, label: `<b>Cu</b>`, title: "Copper", color: ColorVariables.transitionMetal},
  { id: 30, label: `<b>Zn</b>`, title: "Zinc", color: ColorVariables.transitionMetal},
  { id: 31, label: `<b>Ga</b>`, title: "Gallium", color: ColorVariables.transitionMetal},
  { id: 32, label: `<b>Ge</b>`, title: "Germanium", color: ColorVariables.transitionMetal},
  { id: 33, label: `<b>As</b>`, title: "Arsenic", color: ColorVariables.transitionMetal},
  { id: 34, label: `<b>Se</b>`, title: "Selenium", color: ColorVariables.transitionMetal},
  { id: 35, label: `<b>Br</b>`, title: "Bromine", color: ColorVariables.transitionMetal},
  { id: 36, label: `<b>Kr</b>`, title: "Krypton", color: ColorVariables.transitionMetal},
  { id: 37, label: `<b>Rb</b>`, title: "Rubidium", color: ColorVariables.transitionMetal},
  { id: 38, label: `<b>Sr</b>`, title: "Strontium", color: ColorVariables.transitionMetal},
  { id: 39, label: `<b>Y</b>`, title: "Yttrium", color: ColorVariables.transitionMetal},
  { id: 40, label: `<b>Zr</b>`, title: "Zirconium", color: ColorVariables.transitionMetal},
  { id: 41, label: `<b>Nb</b>`, title: "Niobium", color: ColorVariables.transitionMetal},
  { id: 42, label: `<b>Mo</b>`, title: "Molybdeum", color: ColorVariables.transitionMetal},
  { id: 43, label: `<b>Tc</b>`, title: "Technetium", color: ColorVariables.transitionMetal},
  { id: 44, label: `<b>Ru</b>`, title: "Ruthenium", color: ColorVariables.transitionMetal},
  { id: 45, label: `<b>Rh</b>`, title: "Rhodium", color: ColorVariables.transitionMetal},
  { id: 46, label: `<b>Pd</b>`, title: "Palladium", color: ColorVariables.transitionMetal},
  { id: 47, label: `<b>Ag</b>`, title: "Silver", color: ColorVariables.transitionMetal},
  { id: 48, label: `<b>Cd</b>`, title: "Cadmium", color: ColorVariables.transitionMetal},
  { id: 49, label: `<b>In</b>`, title: "Indium", color: ColorVariables.transitionMetal},
  { id: 50, label: `<b>Sn</b>`, title: "Tin", color: ColorVariables.transitionMetal},
  { id: 51, label: `<b>Sb</b>`, title: "Antimony", color: ColorVariables.transitionMetal},
  { id: 52, label: `<b>Te</b>`, title: "Tellurium", color: ColorVariables.transitionMetal},
  { id: 53, label: `<b>I</b>`, title: "Iodine", color: ColorVariables.transitionMetal},
  { id: 54, label: `<b>Xe</b>`, title: "Xenon", color: ColorVariables.transitionMetal},  
  { id: 55, label: `<b>Cs</b>`, title: "Cesium", color: ColorVariables.transitionMetal},
  { id: 56, label: `<b>Ba</b>`, title: "Barium", color: ColorVariables.transitionMetal},
  { id: 57, label: `<b>La</b>`, title: "Lanthanium", color: ColorVariables.lanthanide},
  { id: 58, label: `<b>Ce</b>`, title: "Cerium", color: ColorVariables.lanthanide},
  { id: 59, label: `<b>Pr</b>`, title: "Praseodymium", color: ColorVariables.lanthanide},
  { id: 60, label: `<b>Nd</b>`, title: "Neodymium", color: ColorVariables.lanthanide},
  { id: 61, label: `<b>Pm</b>`, title: "Prometheum", color: ColorVariables.lanthanide},
  { id: 89, label: `<b>Ac</b>`, title: "Actinium", color: ColorVariables.actinide},
  { id: 90, label: `<b>Th</b>`, title: "Thorium", color: ColorVariables.actinide},
]

export default elements;